project_id = "trading03"

[db]
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[analytics]
enabled = false

[auth]
site_url = "http://localhost:8081"
additional_redirect_urls = ["http://localhost:8081/**", "signallab://**"]
enable_signup = true
